# Generated by Django 3.2.4 on 2021-07-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
